# Generated by Django 4.2.7 on 2023-11-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=30)),
                ('contactNumber', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
