# Generated by Django 4.2.7 on 2023-11-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='gastype',
            field=models.CharField(default=30, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='quantity',
            field=models.IntegerField(default=14),
        ),
    ]
