# Generated by Django 4.2.7 on 2023-12-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='address',
            field=models.TextField(default='kkd'),
            preserve_default=False,
        ),
    ]
