# Generated by Django 4.2.7 on 2023-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0005_contactus_registeruser_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='searching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectfields', models.CharField(max_length=30)),
                ('search', models.CharField(max_length=40)),
            ],
        ),
    ]
