# Generated by Django 4.2.7 on 2023-12-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0006_searching'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='searching',
            new_name='searchings',
        ),
    ]
